# D:\AGENTIC_AI\agentic_sdk\cli.py
"""
Command-line interface for Agentic SDK
Windows-compatible version for Aditya Mehra
"""

import click
import json
import sys
import os
from pathlib import Path
from typing import Optional, Dict, Any
import importlib.util

from .agent_base import AgentBase
from .registry import global_registry
from .utils import logger

# Windows-safe printing
def safe_print(message, color=None):
    """Print safely on Windows and other platforms"""
    # Import from __init__ to handle emojis
    from . import _windows_safe_text
    
    message = _windows_safe_text(message)
    
    if color:
        # Use Click for colored output if available
        try:
            click.echo(click.style(message, fg=color))
        except:
            print(message)
    else:
        print(message)

@click.group()
def main():
    """Agentic SDK CLI - Build and manage AI agents"""
    safe_print("🤖 Agentic SDK - Student Founder Edition", "cyan")
    safe_print("👨‍💻 By: Aditya Mehra (B.Tech 2nd Year)", "yellow")

@main.command()
@click.argument('agent_name')
@click.option('--output', '-o', default=None, help='Output file path')
def create(agent_name: str, output: Optional[str]):
    """Create a new agent template"""
    
    if not output:
        output = f"{agent_name.lower().replace(' ', '_')}_agent.py"
    
    template = f'''"""
{agent_name} - AI Agent
Generated by Agentic SDK (Student Founder Edition)
"""

from agentic_sdk import AgentBase, action
import asyncio


class {agent_name.replace(' ', '')}Agent(AgentBase):
    """{agent_name} - AI Agent"""
    
    def __init__(self):
        super().__init__(
            name="{agent_name}",
            description="A specialized agent for {agent_name.lower()} tasks",
            agent_type="specialized",
            skills=["{agent_name.lower()}", "data_processing"]
        )
    
    @action(description="Process data")
    async def process(self, data: dict) -> dict:
        """Process input data"""
        # TODO: Implement your processing logic here
        return {{"status": "processed", "input_data": data}}
    
    @action(description="Analyze data")
    async def analyze(self, data: dict) -> dict:
        """Analyze input data"""
        # TODO: Implement your analysis logic here
        return {{"status": "analyzed", "insights": []}}


if __name__ == "__main__":
    # Quick test
    async def test():
        agent = {agent_name.replace(' ', '')}Agent()
        await agent.start()
        result = await agent.execute("process", data={{"test": "data"}})
        print(f"Result: {{result}}")
        await agent.stop()
    
    asyncio.run(test())
'''
    
    try:
        with open(output, 'w', encoding='cp1252') as f:
            f.write(template)
        
        safe_print(f"✅ Created agent template: {output}", "green")
        safe_print(f"📝 Agent class: {agent_name.replace(' ', '')}Agent", "cyan")
        safe_print(f"🚀 Test with: python {output}", "yellow")
        safe_print(f"📚 Documentation: python -m agentic_sdk.cli --help", "blue")
    
    except Exception as e:
        safe_print(f"❌ Error creating agent: {e}", "red")
        sys.exit(1)

@main.command()
@click.option('--format', '-f', type=click.Choice(['json', 'table', 'simple']), default='table')
def list(format: str):
    """List all registered agents"""
    agents = global_registry.list_agents()
    
    if not agents:
        safe_print("No agents registered. Create one with: python -m agentic_sdk.cli create 'MyAgent'", "yellow")
        return
    
    if format == 'json':
        safe_print(json.dumps(agents, indent=2))
    elif format == 'table':
        safe_print("🤖 Registered Agents:", "cyan")
        safe_print("-" * 60)
        for agent in agents:
            safe_print(f"📛 Name: {agent['name']}", "green")
            safe_print(f"  📝 Description: {agent['description']}")
            safe_print(f"  ⚡ State: {agent['state']}")
            safe_print(f"  🛠️ Skills: {', '.join(agent['skills']) if agent['skills'] else 'None'}")
            safe_print("-" * 60)
    else:
        for agent in agents:
            safe_print(f"{agent['name']} - {agent['state']}")

# Add more commands (run, stats, info) similar to previous version

if __name__ == '__main__':
    main()
